### ISSUE TITLE
ValueError: probabilities contain NaN

### ISSUE THREAD

**Issue by yanli721** [HamPerdredes/SOOD#16]
您好，我运行您的代码，出现了以下几个问题，恳请得到回复和帮助，谢谢!

数据集准备：使用原始DOTA15数据集train和val，运行./tools/data/dota/split_dota_via_list.py（json文件使用data_lists/10p_list.json），获得了train_10_labeled/images和train_10_unlabeled/images，然后运行tools/data/dota/create_empty_annfiles.py，获得train_10_unlabeled/annfiles，不知道以上数据集准备操作是否有误？请问train_10_labeled的annfiles是怎么生成的？

进行训练：运行命令：
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nnodes=1 \
--node_rank=0 --master_addr="127.0.0.1" --nproc_per_node=2 --master_port=25500 \
train.py configs/ssad_fcos/sood_fcos_dota15_10per.py \
--launcher pytorch \
--work-dir ./work-dir
出现报错：
Traceback (most recent call last):
  File "train.py", line 213, in <module>
    main()
  File "train.py", line 202, in main
    train_detector(
  File "/home/yli/SOOD/ssad/apis/train.py", line 155, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/yli/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 128, in run
    iter_loaders = [IterLoader(x) for x in data_loaders]
  File "/home/yli/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 128, in <listcomp>
    iter_loaders = [IterLoader(x) for x in data_loaders]
  File "/home/yli/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 25, in __init__
    self.iter_loader = iter(self._dataloader)
  File "/home/yli/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "/home/yli/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/yli/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 940, in __init__
    self._reset(loader, first_iter=True)
  File "/home/yli/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 971, in _reset
    self._try_put_index()
  File "/home/yli/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1205, in _try_put_index
    index = self._next_index()
  File "/home/yli/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 508, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/yli/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/yli/SOOD/ssad/datasets/samplers/multi_source_sampler.py", line 204, in __iter__
    group = np.random.choice(
  File "mtrand.pyx", line 935, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
Killing subprocess 2575281
Killing subprocess 2575284

请问为什么会出现：ValueError: probabilities contain NaN？您知道怎么样可以解决吗？期待您的回复

**Comment by HamPerdredes** [comment]
从错误来看，可能是给入的数据集路径有问题，如果问题仍未解决的话，请提供相关的config文件和log，希望能帮助到您。

**Comment by Supine-Evelyn** [comment]
您好，我想问一下您这个问题解决了吗，我在自己的数据集上训练的时候，也出现了这个问题。
Traceback (most recent call last):
  File "train.py", line 213, in <module>
    main()
  File "train.py", line 202, in main
    train_detector(
  File "/root/autodl-tmp/SOOD-main/ssad/apis/train.py", line 155, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 128, in run
    iter_loaders = [IterLoader(x) for x in data_loaders]
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 128, in <listcomp>
    iter_loaders = [IterLoader(x) for x in data_loaders]
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 25, in __init__
    self.iter_loader = iter(self._dataloader)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 827, in __init__
    self._reset(loader, first_iter=True)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 857, in _reset
    self._try_put_index()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index
    index = self._next_index()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/root/autodl-tmp/SOOD-main/ssad/datasets/samplers/multi_source_sampler.py", line 203, in __iter__
    group = np.random.choice(
  File "mtrand.pyx", line 935, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN

**Comment by CaptainRoby** [comment]
> 您好，我想问一下您这个问题解决了吗，我在自己的数据集上训练的时候，也出现了这个问题。 Traceback (most recent call last): File "train.py", line 213, in main() File "train.py", line 202, in main train_detector( File "/root/autodl-tmp/SOOD-main/ssad/apis/train.py", line 155, in train_detector runner.run(data_loaders, cfg.workflow) File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 128, in run iter_loaders = [IterLoader(x) for x in data_loaders] File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 128, in iter_loaders = [IterLoader(x) for x in data_loaders] File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 25, in **init** self.iter_loader = iter(self._dataloader) File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 352, in **iter** return self._get_iterator() File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator return _MultiProcessingDataLoaderIter(self) File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 827, in **init** self._reset(loader, first_iter=True) File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 857, in _reset self._try_put_index() File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index index = self._next_index() File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index return next(self._sampler_iter) # may raise StopIteration File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 227, in **iter** for idx in self.sampler: File "/root/autodl-tmp/SOOD-main/ssad/datasets/samplers/multi_source_sampler.py", line 203, in **iter** group = np.random.choice( File "mtrand.pyx", line 935, in numpy.random.mtrand.RandomState.choice ValueError: probabilities contain NaN

i also met this error. Through checking the code snippets with traceback, i change probability para of np.random.choice to a list[1, 0](which is actually same as original), and this can avoid the problem, but training would suddenly suspend in __iter__ stage with high video memory usage but no gpu usage. So i suspect that no usage of gpu in this repo codebase.
