### ISSUE TITLE
an Error: When start SubModulesDistEval, happend ZeroDivisionError 

### ISSUE THREAD

**Issue by Xia-tao** [HamPerdredes/SOOD#4]
Thanks for your wonderful work.I have run this code successfuly,but when start SubModulesDistEval, I meet an Error, can I get your help to solve this problem:
Here is the detail of this error:
2023-05-28 16:21:41,950 - mmrotate - INFO - Saving checkpoint at 3200 iterations
2023-05-28 16:21:43,700 - mmrotate - INFO - Start EMA Update at step 3200
2023-05-28 16:21:43,706 - mmrotate - INFO - Iter [3200/120000]  lr: 2.500e-05, eta: 7:43:24, time: 0.272, data_time: 0.014, memory: 5316, loss_cls_sup: 0.3740, loss_bbox_sup: 0.7086, loss_centerness_sup: 0.6563, loss: 1.7389, grad_norm: 16.1893
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "/home/xiatao/projects/SOOD/train.py", line 213, in <module>
    main()
  File "/home/xiatao/projects/SOOD/train.py", line 202, in main
    train_detector(
  File "/home/xiatao/projects/SOOD/ssad/apis/train.py", line 155, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/xiatao/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/xiatao/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 70, in train
    self.call_hook('after_train_iter')
  File "/home/xiatao/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/xiatao/projects/SOOD/ssad/utils/hooks/submodules_evaluation.py", line 41, in after_train_iter
    self._do_evaluate(runner)
  File "/home/xiatao/projects/SOOD/ssad/utils/hooks/submodules_evaluation.py", line 79, in _do_evaluate
    results = multi_gpu_test(
  File "/home/xiatao/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmdet/apis/test.py", line 107, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/xiatao/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/xiatao/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/xiatao/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/home/xiatao/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/home/xiatao/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/home/xiatao/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/xiatao/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 229, in __iter__
    for idx in self.sampler:
  File "/home/xiatao/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/mmdet/datasets/samplers/distributed_sampler.py", line 47, in __iter__
    math.ceil(self.total_size / len(indices)))[:self.total_size]
ZeroDivisionError: division by zero

**Comment by hh123445** [comment]
ZeroDivisionError: division by zero可能是因为没有读到验证集数据，将config中的验证集路径由相对路径改为绝对路径可能可以解决

**Comment by zlx913** [comment]
请问楼主怎么解决的这个问题，我遇到一样的报错
